### ISSUE TITLE
Broken link to Routing in Vuejs docs.

### ISSUE THREAD

**Issue by nick-nds** [vuejs/docs#2203] opened 2023-02-03 19:04 UTC
![image](https://user-images.githubusercontent.com/41892719/216686041-f91cfaba-8af9-41bb-beba-313d0c86e36c.png)

![image](https://user-images.githubusercontent.com/41892719/216685686-297bd3dd-71f7-46eb-9215-1f45d278b644.png)

Not able to navigate to Routing in Vue docs.
URL: https://vuejs.org/guide/scaling-up/routing.html

**Comment by xfq** [comment] 2023-02-06 11:25
I'm not able to reproduce this using Safari 16.3:

<img width="1377" alt="safari" src="https://user-images.githubusercontent.com/2863444/216959637-6d5d417c-0668-4d6d-949c-fca5e2246375.png">

**Comment by Navidkhm** [comment] 2023-02-25 08:42
@nick-nds I checked this issue and it's not there anymore. please close this issue.

**Comment by nick-nds** [comment] 2023-02-28 21:09
@Navidkhm @xfq  I guess it has been fixed.

**Comment by Navidkhm** [comment] 2023-03-02 16:35
@nick-nds  
I think so too.
can you close the issue?

**Comment by skirtles-code** [comment] 2023-03-02 20:59
We get problems like this reported fairly regularly. The 'Page Not Found' message is a bit misleading, as it gets shown in various scenarios and it doesn't necessarily indicate a problem on the server. If your internet connection temporarily drops when navigating to a new page then you'll see that same message. We probably need a better error page, to give us some more hints about exactly what went wrong.

**Closed by skirtles-code** 2023-03-02 20:59 UTC

**Comment by Navidkhm** [comment] 2023-03-03 07:31
@skirtles-code
exactly.
thank you
