### ISSUE TITLE
Is there a plan to update Style Guide for Composition API?

### ISSUE THREAD

**Issue by awxiaoxian2020** [vuejs/docs#2106] opened 2022-11-23 12:49 UTC

**Comment by NataliaTepluhina** [comment] 2022-12-01 12:02
Yes, we plan to do so. Closing as a duplicate of https://github.com/vuejs/docs/issues/2030

**Closed by NataliaTepluhina** 2022-12-01 12:02 UTC

**Comment by awxiaoxian2020** [comment] 2022-12-02 06:39
@NataliaTepluhina My question is that there is an actual date or schedule for update this guide?
