### ISSUE TITLE
Uneven cursor styling value in the website

### ISSUE THREAD

**Issue by priyanshk20** [vuejs/docs#1117] opened 2021-06-30 06:14 UTC
The `<h>` tags and the `<p>` tags all over the website are set as `cursor:initial;` which does not look good and looks uneven as some tags have `cursor:default;` value set. It would be better to have all the `<h>` and `<p>` tags to have `cursor:default;` property, to make it look even.

**Comment by priyanshk20** [comment] 2021-06-30 06:17
Can I work on this issue?

**Comment by skirtles-code** [comment] 2021-07-08 10:00
Could you provide an example of a page where you're seeing this problem? Maybe a picture would help explain? I'm not seeing `cursor: initial` myself.

**Comment by priyanshk20** [comment] 2021-07-10 07:06
@skirtles-code That is a default cursor property. You can see that on the main page itself on the browser when you hover on those elements. It's not a major issue as such but just the page will look more even on cursor hovers.

**Comment by NataliaTepluhina** [comment] 2022-02-07 11:46
Closing as the issue is not relevant after switching to new docs

**Closed by NataliaTepluhina** 2022-02-07 11:46 UTC
Labels: style-improvement
