### ISSUE TITLE
Sharing a link to a specific page with Options or Composition pre-selected

### ISSUE THREAD

**Issue by CyberAP** [vuejs/docs#1482] opened 2022-02-03 22:45 UTC
This is an issue for the new upcoming docs currently hosted at staging.vuejs.org.

How do I share a link to a page that has Options API or Composition API preference pre-configured?

This is probably a design limitation of the docs and hopefully can be addressed.

**Comment by Rolanddoda** [comment] 2022-03-13 16:21
Yup, that's an issue I've run to, multiple times. 

The last time, I saw a link to https://vuejs.org/guide/essentials/reactivity-fundamentals.html#stateful-methods and I had composition API preference enabled and I couldn't see the page I wanted. That can be misleading.

**Comment by dasDaniel** [comment] 2022-04-07 22:58
This 💯
Without a way to specify in the url which docs to use, they are hard to send reference links via LMGTFY or even non passive-aggressive means.

**Comment by skirtles-code** [comment] 2022-08-30 10:09
#1901 is a duplicate of this issue, but as the conversation about this enhancement is at a more advanced stage on that issue I'm going to close this one.

**Closed by skirtles-code** 2022-08-30 10:09 UTC
Labels: enhancement, new version
