### ISSUE TITLE
[OTHERS] Can't find Vue Style Guides in Vue Website

### ISSUE THREAD

**Issue by at-the-vr** [vuejs/docs#2321] opened 2023-04-15 16:08 UTC
I see [Vue Style Guides](https://vuejs.org/style-guide/) is a publicly accessible page (really helpful) but I cant find it anywhere in [vuejs.org](https://vuejs.org/)

**Comment by brc-dd** [comment] 2023-04-15 16:10
Duplicate of #2030

**Comment by at-the-vr** [comment] 2023-04-15 16:11
I am sorry to miss the Issue, should i close it Divyansh ?

**Comment by brc-dd** [comment] 2023-04-15 16:11
Yeah.

**Closed** 2023-04-15 16:12 UTC
