### ISSUE TITLE
Can we get some more information on why there is no guarantee that elements are in the correct order when using the refs array feature?

### ISSUE THREAD

**Issue by daniilgri** [vuejs/docs#2598] opened 2023-12-08 15:50 UTC
Section: https://vuejs.org/guide/essentials/template-refs#refs-inside-v-for

In the section "Refs inside v-for", it would be great to have an explanation of why Vue does not guarantee the correct order of elements when using `v-for` with `ref="someRefs"`. It might be worth adding some notes on how to solve this problem or what approach we should use instead of it to have the same order of elements as a source array has.
![image](https://github.com/vuejs/docs/assets/19237333/aeb892f8-0334-4d36-8b5a-e793a6fada58)

**Comment by jacekkarczmarczyk** [comment] 2023-12-08 15:58
Duplicate of https://github.com/vuejs/docs/issues/1961

**Closed** 2023-12-08 17:11 UTC
