### ISSUE TITLE
Language indicator text in code examples overlaps with new content available dialog box.

### ISSUE THREAD

**Issue by goshaGloss** [vuejs/docs#1265] opened 2021-10-02 10:31 UTC
![modal bug](https://user-images.githubusercontent.com/86202712/135712569-3f7c34ac-32a4-4f31-a0c4-b1e38301789f.png)
I think, you should increase z-index of the dialog box.

**Comment by skirtles-code** [comment] 2021-10-03 15:04
Thanks for the report. I think this is a duplicate of #865.

As I recall, changing the `z-index` isn't as simple as it sounds because there are various other `z-index` values coming from third-party plugins and they'd all need overriding too.

It should be fixed when we migrate to VitePress, currently work-in-progress on the `next` branch.

**Closed by skirtles-code** 2021-10-03 15:04 UTC
