### ISSUE TITLE
Suggest: Vue3.0 document cross-domain switching Chinese and English translation routing problem

### ISSUE THREAD

**Issue by NaCoLiu** [vuejs/docs#1080] opened 2021-06-06 07:02 UTC
Suggest: Vue3.0 document cross-domain switching Chinese and English translation routing problem.
It is recommended to modify the translation items of the file system. Obtain the current route and directly point to the route to the Chinese station.
https://github.com/vuejs/docs-next-zh-cn/issues/549

**Comment by NaCoLiu** [comment] 2021-06-06 08:16
zh-CN dosc website developers are ready

**Comment by skirtles-code** [comment] 2021-06-06 10:30
I think this is a duplicate of #932.

I don't think this is feasible as new pages get added to the docs all the time and the translations are invariably behind. If you have a suggestion for how to solve that problem please let us know.

**Comment by Jinjiang** [comment] 2021-06-06 13:47
Hi, @skirtles-code I understand your concern, which is not a technical one. However, in v2 we already implemented that through [this](https://github.com/vuejs/vuejs.org/blob/master/themes/vue/layout/partials/language_dropdown.ejs). I'm afraid of users' side, they feel the experience going backward. Then what about we just take this concern as the v2 is right now and keep the experience the same? :-)
Thanks.

**Comment by NaCoLiu** [comment] 2021-06-06 14:07
Only add some code, no need recode project, this suggestion will be some dev, thx

**Comment by skirtles-code** [comment] 2021-07-08 09:25
This is now implemented. See #1105 for details. It includes some improved handling for 404 errors, which will only be fully effective once it is pulled into the translations.

**Closed by skirtles-code** 2021-07-08 09:25 UTC
Labels: enhancement
