### ISSUE TITLE
Double ads on the website (casually happens)

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/docs#1128] opened 2021-07-06 13:48 UTC
![image](https://user-images.githubusercontent.com/206848/124610763-5ad6e380-dea3-11eb-9014-22e0dffae536.png)

It's quite weird since sometimes when I (usually the first time of the day) open the website, there would be 2 of the same ads rendered like above.

When I refreshed the page then it went back to normal.

My env is Safari in macOS Monterey. But I remember before upgrading macOS to this version, it also happened casually in Safari.

It's hard to debug because it didn't happen every time. Just would like to take a note here first.

Thanks.

**Comment by Jinjiang** [comment] 2021-07-06 13:56
I'd like to share 2 more screenshots for the duplicated side ads and bottom ads. Hope those are helpful:

Side ads (with 2 different ids `carbonads_1` and `carbonads`):
![image](https://user-images.githubusercontent.com/206848/124611744-4fd08300-dea4-11eb-8f0a-977b9c9f20d0.png)

Bottom ads (with the same id `_default_`):
![image](https://user-images.githubusercontent.com/206848/124612106-a3db6780-dea4-11eb-90d2-6cd83c6403a2.png)

Thanks.

**Comment by NataliaTepluhina** [comment] 2022-02-07 11:46
Closing as the issue is not relevant after switching to new docs

**Closed by NataliaTepluhina** 2022-02-07 11:46 UTC
Labels: style-improvement
