### ISSUE TITLE
Add Reactivity Changes section to Migration Guide

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs#420] opened 2020-08-19 20:24 UTC
No longer need Vue.set and can update arrays and objects directly.

**Comment by itsgoingd** [comment] 2020-09-19 14:43
The new reactivity system also comes with a new limitation - changes to objects that don't go through the proxy won't get picked up by Vue.

Ran into this while trying to update a Vue 2 project, here is my original issue with a simple reproduction - https://github.com/vuejs/vue-next/issues/2171

Not sure how common this use case is, but it's pretty important to mention imo. Also the migration path for this issue is not very clear.

**Comment by LinusBorg** [comment] 2020-09-19 15:07
Worth mentioning here is that even in Vue 2, we recommend to refrain from observing non-plain objects, precisely because there were other edge cases in Vue's reactivity that could lead to weird behavior when i.e. the class had some complex internal behavior in manipulating its properties etc.

https://vuejs.org/v2/api/#data

> the object must be plain. [...] A rule of thumb is that data should just be data - it is not recommended to observe objects with their own stateful behavior.

So while what you did in your case has worked in Vue 2 for you so far, you did something that was not recommended even then. Now you just came across a different kind of edge case that now keeps your solution from working.

----

Nonetheless we could mention this class of caveats somewhere around here: https://v3.vuejs.org/guide/reactivity.html#proxy-vs-original-identity

**Comment by scaredyfish** [comment] 2020-11-30 19:20
The lack of Vue.set really confused me for some time. It should at least be documented under https://v3.vuejs.org/guide/migration/introduction.html#removed-apis

**Comment by NataliaTepluhina** [comment] 2021-06-17 08:51
Closing an issue as related PR was merged

**Closed by NataliaTepluhina** 2021-06-17 08:51 UTC
Labels: vue-3-migration-guide
