### ISSUE TITLE
Search breaks if menu has been opened

### ISSUE THREAD

**Issue by thedamon** [vuejs/docs#598] opened 2020-10-05 12:58 UTC
This is on iOS 14, iPhone 8 Plus. 

If I click search either nothing happens, or an empty space appears above the page which is then disabled. I think this is only if I have opened the site menu previously to clicking search. Going "back" fixes it and brings the functioning search modal back

![image](https://user-images.githubusercontent.com/1375267/95082310-dcb59880-06e8-11eb-8e6a-705c3b480b2b.jpeg)

**Comment by gtsiolis** [comment] 2020-11-05 22:22
Can't reproduce this. 😭

**Comment by thedamon** [comment] 2020-11-10 19:59
I tried it again.. looks like the issue happens if I am scrolled down on the page.

**Comment by NataliaTepluhina** [comment] 2022-04-13 08:12
Closing as it doesn't happen on the new website

**Closed by NataliaTepluhina** 2022-04-13 08:12 UTC
Labels: style-improvement
