### ISSUE TITLE
Code blocks display code lang.

### ISSUE THREAD

**Issue by karukenert** [vuejs/docs#1935] opened 2022-08-26 06:59 UTC
<img width="711" alt="image" src="https://user-images.githubusercontent.com/46687296/186842042-ffd9de21-2496-416b-86e2-d0ed031f3993.png">

**Comment by karukenert** [comment] 2022-08-26 07:01
The language is already show in pseudo-element ::before, but the span with the lang is still displayed.
<img width="340" alt="image" src="https://user-images.githubusercontent.com/46687296/186842288-cfbf5c15-18a1-4609-ab4f-5e9c59eee4ac.png">

**Comment by skirtles-code** [comment] 2022-08-26 07:14
This appears to have been introduced in f54aab387042460e8e24c1ff9a82d5fe8ac6b656, which upgraded VitePress to the latest version.

**Comment by tony19** [comment] 2022-08-26 20:00
Duplicate of #1927

**Comment by skirtles-code** [comment] 2022-08-26 23:03
The problem seems to be in `vuejs/theme`, rather than VitePress itself: https://github.com/vuejs/theme/issues/69

**Comment by skirtles-code** [comment] 2022-08-30 18:01
This has now been fixed and applied to the docs.

**Closed by skirtles-code** 2022-08-30 18:01 UTC
Labels: bug
