### ISSUE TITLE
Fix question number style and layout

### ISSUE THREAD

**Issue by ksdhir** [vuejs/docs#1115] opened 2021-06-29 13:07 UTC
The question number panel has two issues:

-  It is not parallel to the lines of code
- The panel isn't limited to the size of code-box and sometimes overlaps the text below.

![Screenshot from 2021-06-29 18-36-58](https://user-images.githubusercontent.com/44022086/123802507-02cf3880-d909-11eb-93fb-1693ad1b1f59.png)

Not sure if this is the browser issue but I'm using Google Chrome Version 91.0.4472.114.

**Comment by NataliaTepluhina** [comment] 2022-02-07 11:46
Closing as the issue is not relevant after switching to new docs

**Closed by NataliaTepluhina** 2022-02-07 11:46 UTC
